UserRecordForm/UserRecordForm/Models/UserRecord.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace UserRecordForm.Models
{
    
    public class UserRecord
    {
        public Nullable<int> userId { get; set; }
        public string email { get;set;}
        public string username  { get; set; }
        public string password { get; set; }
        public string mnumber { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address   { get; set; }   

        public string dropdownCity { get; set; }   
        public Nullable<System.DateTime> dob { get; set; }  
        
        public int age { get; set; }  
        public int ssc_total_mark { get; set; }  
        public int ssc_obtained_mark { get; set; }  
        public float percentage_ssc { get; set; }
        public List<UserRecord> showAllRecords { get; set; }

        public List<UserRecord> sortedList { get; set; }


    }
}
/*
namespace UserRecordForm.Models
{
    using System;
    using System.Collections.Generic;

    public partial class UserRec1
    {
        public int userId { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string mnumber { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public string dropdownCity { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> ssc_total_mark { get; set; }
        public Nullable<int> ssc_obtained_mark { get; set; }
        public Nullable<decimal> percentage_ssc { get; set; }
        public List<UserRec1> showAllRecords { get; set; }


    }
}*/

UserRecordForm/UserRecordForm/Controllers/UserRec1Controller.cs
/*using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserRecordForm.Models;

namespace UserRecordForm.Controllers
{
    public class UserRec1Controller : Controller
    {
        private UserRecordEntities db = new UserRecordEntities();

        // GET: UserRec1
        public ActionResult Index()
        {
            return View(db.UserRecord.ToList());
        }

        // GET: UserRec1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserRec1 userRec1 = db.UserRecord.Find(id);
            if (userRec1 == null)
            {
                return HttpNotFound();
            }
            return View(userRec1);
        }

        // GET: UserRec1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserRec1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,email,username,password,mnumber,firstName,LastName,address,dropdownCity,dob,age,ssc_total_mark,ssc_obtained_mark,percentage_ssc")] UserRec1 userRec1)
        {
            if (ModelState.IsValid)
            {
                db.UserRecord.Add(userRec1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userRec1);
        }

        // GET: UserRec1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserRec1 userRec1 = db.UserRecord.Find(id);
            if (userRec1 == null)
            {
                return HttpNotFound();
            }
            return View(userRec1);
        }

        // POST: UserRec1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,email,username,password,mnumber,firstName,LastName,address,dropdownCity,dob,age,ssc_total_mark,ssc_obtained_mark,percentage_ssc")] UserRec1 userRec1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userRec1).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userRec1);
        }

        // GET: UserRec1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserRec1 userRec1 = db.UserRecord.Find(id);
            if (userRec1 == null)
            {
                return HttpNotFound();
            }
            return View(userRec1);
        }

        // POST: UserRec1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserRec1 userRec1 = db.UserRecord.Find(id);
            db.UserRecord.Remove(userRec1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
*/

UserRecordForm/UserRecordForm/Controllers/UserRecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
/*using UserRecordForm.Models.UserRecord;*/
using UserRecordForm.DataAccess;
using UserRecordForm.Models;
using System.Text.RegularExpressions;

namespace UserRecordForm.Controllers
{

    public class UserRecordController : Controller
    {

/*        private readonly ILogger<UserRecordController> _logger;
*/
        // GET: UserRecord

       /* public UserRecordController(ILogger<UserRecordController> logger)
        {
            _logger = logger;   
        }*/


        public ActionResult InsertUser(UserRecord model)
        {

            if (String.IsNullOrEmpty(model.firstName))
            {
                ModelState.AddModelError("FirstName", "FirstName is required");
            }
            /*
            if (String.IsNullOrEmpty(model.lastName))
            {
                ModelState.AddModelError("lastName", "lastName is required");
            }
           
            if (string.IsNullOrEmpty(model.email))
            {
                ModelState.AddModelError("Email", "Email is required.");
            }
            else if (!IsValidEmail(model.email))
            {
                ModelState.AddModelError("Email", "Invalid email format.");
            }
            if (String.IsNullOrEmpty(model.username))
            {
                ModelState.AddModelError("username", "username is required");
            }
            if (String.IsNullOrEmpty(model.mnumber))
            {
                ModelState.AddModelError("Mobile Number", "Mobile Number is required");
            }
            if (String.IsNullOrEmpty(model.password))
            {
                ModelState.AddModelError("Password", "Password is required");
            }
            if (String.IsNullOrEmpty(model.address))
            {
                ModelState.AddModelError("Address", "Address is required");
            }
            if (String.IsNullOrEmpty(model.address))
            {
                ModelState.AddModelError("Address", "Address is required");
            }
            if (String.IsNullOrEmpty(model.ssc_total_mark.ToString()))
            {
                ModelState.AddModelError("ssc_total_mark", "Total Marks is required");
            }
            if (String.IsNullOrEmpty(model.ssc_obtained_mark.ToString()))
            {
                ModelState.AddModelError("ssc_obtained_mark", "Obtained Marks is required");
            }

*/

            if (ModelState.IsValid)
            {
                DataAccessLayer objDB = new DataAccessLayer();
                string result = objDB.InsertData(model);
                TempData["result1"] = result;
                return Json(result, JsonRequestBehavior.AllowGet);
               
            }

            return View(model);
        }

        private bool IsValidEmail(string email)
        {
          
            return Regex.IsMatch(email, @"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,4}\b");
        }

        /*public ActionResult InsertUser()
        {
            return View();
        }*/

        /* [HttpPost]
         public JsonResult InsertUser(UserRecord objuser)

         {
 *//*            _logger.LogInformation("This is an informational log message in index Method.");
 *//*
             DataAccessLayer objDB = new DataAccessLayer();
             string result = objDB.InsertData(objuser);
             TempData["result1"] = result;
             return Json(result, JsonRequestBehavior.AllowGet);

         }*/

        [HttpGet]
      
        public ActionResult ViewAll(string sortBy,int Page, int? pageSize, string searchText = "")
        {

/*            _logger.LogInformation("This is an informational log message in View All Method.");
*/
            UserRecord rec = new UserRecord();
            DataAccessLayer objDB = new DataAccessLayer();

            if (searchText =="" || searchText==null)
            
            {

                int itemsPerPage = pageSize ?? 4 ;
                /*int currentPage = Convert.ToInt32(Page);*/
                int currentPage = Page;
                int skipCount = (currentPage - 1) * itemsPerPage;
                /*rec.showAllRecords = objDB.ViewAllUser();*/
                rec.showAllRecords = objDB.paginationView( itemsPerPage, skipCount);

                ViewBag.UserIdSortParm = String.IsNullOrEmpty(sortBy) ? "userId_desc" : "";
                ViewBag.NameSortParm = sortBy == "name" ? "name_desc" : "name";
                ViewBag.addressSortParm = sortBy == "address" ? "address_desc" : "address";
                ViewBag.markSortParm = sortBy == "ssc_obtained_mark" ? "marks_desc" : "ssc_obtained_mark";
                ViewBag.ageSortParm = sortBy == "age" ? "age_desc" : "age";
                ViewBag.lastNameParm = sortBy == "lastName" ? "lastName_desc" : "lastName";
                ViewBag.PageSize = itemsPerPage;
                switch (sortBy)
                {

                    case "name_desc":
                        rec.sortedList = rec.showAllRecords.OrderByDescending(u => u.firstName).ToList();
                        break;
                    case "name":
                        rec.sortedList = rec.showAllRecords.OrderBy(u => u.firstName).ToList();
                        break;
                    case "lastName_desc":
                        rec.sortedList = rec.showAllRecords.OrderByDescending(u => u.lastName).ToList();
                        break;
                    case "lastName":
                        rec.sortedList = rec.showAllRecords.OrderBy(u => u.lastName).ToList();
                        break;
                    case "age_desc":
                        rec.sortedList = rec.showAllRecords.OrderByDescending(u => u.age).ToList();
                        break;
                    case "age":
                        rec.sortedList = rec.showAllRecords.OrderBy(u => u.age).ToList();
                        break;
                    case "address_desc":
                        rec.sortedList = rec.showAllRecords.OrderByDescending(u => u.address).ToList();
                        break;
                    case "address":
                        rec.sortedList = rec.showAllRecords.OrderBy(u => u.address).ToList();
                        break;
                    case "marks_desc":
                        rec.sortedList = rec.showAllRecords.OrderByDescending(u => u.ssc_obtained_mark).ToList();
                        break;
                    case "ssc_obtained_mark":
                        rec.sortedList = rec.showAllRecords.OrderBy(u => u.ssc_obtained_mark).ToList();
                        break;
                    
                    case "userId_desc":
                        rec.sortedList = rec.showAllRecords.OrderByDescending(u => u.userId).ToList();
                        break;
                    default:
                        rec.sortedList = rec.showAllRecords.OrderBy(u => u.userId).ToList();
                        break;
                }


                Console.WriteLine("after exception");
                ViewBag.currentPage = currentPage;
                ViewBag.itemsPerPage = itemsPerPage;
                ViewBag.skipCount = skipCount;

                int totalRecords = objDB.totalReocordCount();
                int totalPages = (int)Math.Ceiling((double)totalRecords / itemsPerPage);

                ViewBag.totalPages = totalPages;

                return View(rec);

            }
            else  {

                ViewBag.NameSortParm = String.IsNullOrEmpty(sortBy) ? "name_desc" : "";
                ViewBag.addressSortParm = sortBy == "address" ? "address_desc" : "address";
                ViewBag.markSortParm = sortBy == "ssc_obtained_mark" ? "marks_desc" : "ssc_obtained_mark";
                ViewBag.markSortParm = sortBy == "age" ? "age_desc" : "age";
                ViewBag.searchText = searchText;


                rec.showAllRecords = objDB.ViewSearchResult(searchText);

                switch (sortBy)
                {
                    case "name_desc":
                        rec.sortedList = rec.showAllRecords.OrderByDescending(u => u.firstName).ToList();
                        break;
                    case "address_desc":
                        rec.sortedList = rec.showAllRecords.OrderByDescending(u => u.address).ToList();
                        break;
                    case "address":
                        rec.sortedList = rec.showAllRecords.OrderBy(u => u.address).ToList();
                        break;
                    case "marks_desc":
                        rec.sortedList = rec.showAllRecords.OrderByDescending(u => u.ssc_obtained_mark).ToList();
                        break;
                    case "ssc_obtained_mark":
                        rec.sortedList = rec.showAllRecords.OrderBy(u => u.ssc_obtained_mark).ToList();
                        break;
                    default:
                        rec.sortedList = rec.showAllRecords.OrderBy(u => u.firstName).ToList();
                        break;
                }
                return View(rec);
            }

        }

/*
        [HttpPost]
        [ActionName("ViewSearch")]

        public ActionResult ViewAll(string searchText)
        {
            DataAccessLayer objDb = new DataAccessLayer();
            UserRecord rec = new UserRecord();
            rec.showAllRecords = objDb.ViewSearchResult(searchText);
            return View("ViewAll", rec);
        }*/



        [HttpGet]
        public ActionResult DeleteUser(int userId,int Page)
        {
            DataAccessLayer objDb = new DataAccessLayer();
            if (objDb.DeleteUser(userId)) { 
                ViewBag.AlertMsg = "Student deleted Successfully";
               }
            ModelState.Clear();
            return RedirectToAction("ViewAll",new { Page = Page});
        }
        [HttpGet]

UserRecordForm/UserRecordForm/Views/UserRecord/EditUser.cshtml
@model UserRecordForm.Models.UserRecord
@{
    ViewBag.Title = "EditUser";
}

<h2>EditUser</h2>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>


    </title>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/form2.js"></script>
    <style type="text/css">




.container1 {
   position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.container2 {
 position: fixed;
  top: 53%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.container3 {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);

}
html, body {
  height: 100%;
  margin: 0;
  padding: 0;
}
.col-md-6 {
    background-color: lightgray;
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  font-family: Arial, sans-serif;
  font-size: 18px;
  color: #333;
  width: 400px;
  max-width: 90%;
}


.radio-group {
  text-align: center;
}

.radio-group label {
  display: inline-block;
  margin: 0 10px;
}

.form-group input {
    max-width: 280px;
}
.radio-group input[type="radio"] {
  vertical-align: middle;
}

 @*   margin-right: 290px;
}*@
    </style>
</head>
@using (Html.BeginForm("EditUser", "UserRecord", FormMethod.Post))
{
   
        <div id="div1" class="container1" >
            <div class="col-md-6" >
                <div class="form-group" style="display: none;">
                @Html.EditorFor(model => model.userId, new { htmlAttributes = new { @class = "form-control" } })
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    <div id="demo"></div>

                </div>

                <div class="form-group" >
                    <label for="username">Username</label>
                    @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                    <div id="demo"></div>

                </div>
                <div class="form-group" style="display: none;">
                    <label for="password">Password</label>
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" , @readonly="true" } })
                    <div id="demo"></div>

                </div>
                <div class=" form-group">
                    <label for="mnumber">Mobile Number</label>
                    @Html.EditorFor(model => model.mnumber, new { htmlAttributes = new { @class = "form-control" } })
                    <div id="demo"></div>
                </div>


                <div class="col">
                    <button type="button" id="next1" class="btn btn-primary">NEXT</button>
                </div>
            </div>
        </div>
    


        <div id="div2" class="container2" style="display: none;">
            <div class="col-md-6">
                    <h2>Pesronal Record</h2>
                    <br />
                    <div class="form-group">
                        <label for="firstName">First Name</label>
                        @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                        <div id="demo"></div>
                    </div>
                    <div class="form-group">
                        <label for="lastName">Last Name</label>
                        @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                        <div id="demo"></div>
                    </div>


                    <div class="form-group">
                        <label for="address">Address</label>
                        @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })

                        <div id="demo"></div>

                    </div>
                    <div class="form-group">
                        <label for="city">City</label>
                        @Html.DropDownList("dropdownCity", new SelectList(new[]
                             {
                                 new { Value = "-1", Text = "Choose an option" },
                                 new { Value = "Jalna", Text = "Jalna" },
                                 new { Value = "Kolkata", Text = "Kolkata" },
                                 new { Value = "Chennai", Text = "Chennai" },
                                 new { Value = "Shri_nagar", Text = "Shri Nagar" }
                             }, "Value", "Text"), new { @class = "form-control custom-select browser-default", id = "dropdownCity" })
                    </div>
                    <div id="demo"></div>
                   
                    <div class=" form-group" style="display: none;">
                        <label class="date">Date Of birth: </label>
@*                        @Html.EditorFor(model => model.dob, new { htmlAttributes = new { @class = "form-control" } })
*@                        @Html.TextBoxFor(model => model.dob, "{0:yyyy-MM-dd}", new { @class = "form-control" })

                        <div id="demo"></div>

                    </div>
                    <div class=" form-group" style="display: none;">
                        <label class="age">Age : </label>
                        <input type="text" id="age" class="form-control" readonly>
                        <div id="demo"></div>

                    </div>

                    <button type="button" id="prev2" class="btn btn-primary">PREV</button>

                    <button type="button" id="next2" class="btn btn-primary">NEXT</button>

            </div>
        </div>



        <div id="div3" class="container3" style="display: none;">
            <div class="col-md-6">

                    <h2>Educational Details</h2>
                    <div class=" form-group">
                        <label for="total_mark">Total Marks in SSC : </label>
                        @Html.EditorFor(model => model.ssc_total_mark, new { htmlAttributes = new { @class = "form-control" } })
                        <div id="demo"></div>

                    </div>
                    <div class=" form-group">
                        <label for="obtained_mark">Obtained Marks in SSC : </label>
                        @Html.EditorFor(model => model.ssc_obtained_mark, new { htmlAttributes = new { @class = "form-control" } })
                        <div id="demo"></div>

                    </div>
                    <div class=" form-group">
                        <label for="Percentage">Percentage : </label>
                        @Html.EditorFor(model => model.percentage_ssc, new { htmlAttributes = new { @readonly = "readonly" , @class = "form-control" } })
                        <input type="button" name="get" id="get1" value="Get">
                    </div>
                    <button type="button" id="prev3" class="btn btn-primary">PREV</button>


                    <input type="submit" value="Submit" />
                    <div>

                    </div>


            </div>


            </div>
    

}

UserRecordForm/UserRecordForm/Views/UserRecord/ViewAll.cshtml
@model UserRecordForm.Models.UserRecord


@{
    ViewBag.Title = "ViewAllRecord";
}


<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <script src="    https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <style>
        .input-container {
            position: relative;
        }

        .clear-button {
            position: absolute;
            top: 50%;
            right: 10px;
            transform: translateY(-50%);
            cursor: pointer;
        }
    </style> 
</head>
<body>
    <h2>View All Records</h2>
    <div style="font-family:Arial black;">
        <br />
        <p>
            @Html.ActionLink(linkText: "New User", actionName: "InsertUser", controllerName: "UserRecord")
        </p>


        @using (Html.BeginForm("ViewAll", "UserRecord", FormMethod.Get))
        {

            <label for="pageSize">Records Per Page:</label>
            <input type="number" id="itemPerPage" name="pageSize" style="width:50px;height:30px;border:solid" placeholder="@ViewBag.PageSize" />
            @*<button type="submit" id="recordPerPageSubmit" style="width:50px;height:25px">GET</button>*@

            @Html.Hidden("sortBy", "null")
            @Html.Hidden("Page", "1")

       
            <div class="input-container" col-md-6">
                <input type="search" name="searchText" id="searchQuery" style="width:500px" placeholder="Search here" value="@ViewBag.searchText" />
                <span class="clear-button">&times;</span>

                <button type="submit" id="searchSubmit" style="width:100px" value="Search">Search</button>
            </div>
        }

        <table class="table table-bordered table-hover" id="myTable">
            <tr style="background-color:lightgoldenrodyellow">
                <th>
                    @Html.RouteLink("ID", "ViewAllUser", new { sortBy = ViewBag.UserIdSortParm, Page = Request.QueryString["Page"] })

                </th>

                <th>
                    @Html.RouteLink("First Name", "ViewAllUser", new { sortBy = ViewBag.NameSortParm, Page = Request.QueryString["Page"] })

                    @*                    @Html.ActionLink("firstName", "ViewAll", new { sortBy = ViewBag.NameSortParm }, new { Page = 1 })
                    *@
                </th>
                <th>
                    @Html.RouteLink("Last Name", "ViewAllUser", new { sortBy = ViewBag.lastNameParm, Page = Request.QueryString["Page"] })

                </th>
                <a href="~/Content/bootstrap.css.map">~/Content/bootstrap.css.map</a>
                <th>
                    @Html.RouteLink("Address", "ViewAllUser", new { sortBy = ViewBag.addressSortParm, Page = Request.QueryString["Page"] })

                </th>
                <th>
                    @Html.LabelFor(model => model.dropdownCity, "City")
                </th>
                <th>
                    @Html.RouteLink("Age", "ViewAllUser", new { sortBy = ViewBag.ageSortParm, Page = Request.QueryString["Page"] })

                </th>
                <th>
                    @Html.RouteLink("Marks in SSC", "ViewAllUser", new { sortBy = ViewBag.markSortParm, Page = Request.QueryString["Page"] })


                </th>
                <th>
                    Action
                </th>

            </tr>
            @foreach (var item in Model.sortedList)
            {



                <tr style="background-color:ghostwhite">
                    <td>
                        @Html.DisplayFor(ModelItem => item.userId)
                    </td>

                    <td>
                        @Html.DisplayFor(ModelItem => item.firstName)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.lastName)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.address)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.dropdownCity)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.age)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.ssc_obtained_mark)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "EditUser", new { userId = item.userId }) |
                        @Html.ActionLink("Delete", "DeleteUser", new { userId = item.userId, Page = Request.QueryString["Page"] }, new { onclick = "return confirm ( 'Are you sure wants to delete?' );" })
                        @*  @using  (Html.BeginForm("DeleteUser","UserRecord",new { id = item.userId }, FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                                <button type="submit" onclick = "return confirm ( 'Are you sure wants to delete?' );" >Delete</button>
                        } *@
                    </td>


                </tr>
            }
        </table>

    </div>
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.totalPages; i++)
        {
            <li class="@(i == ViewBag.currentPage ? "page-item active" : "page-item")">
                <a class="page-link" href="@Url.Action("ViewAll", new { Page = i })">@i</a>
            </li>

        }
    </ul>
</body>
</html>

@*<ul class="pagination">
    @if (ViewBag.currentPage > 1)
    {
        <a href="@Url.Action("PaginationView", new { page = ViewBag.currentPage - 1 })">Previous</a>
    }

    @for (int i = 1; i <= ViewBag.totalPages; i++)
    {
        if (i == ViewBag.currentPage)
        {
            <span>@i</span>
        }
        else
        {
            <a href="@Url.Action("PaginationView", new { page = i })">@i</a>
        }
    }

    @if (ViewBag.currentPage < ViewBag.totalPages)
    {
        <a href="@Url.Action("PaginationView", new { page = ViewBag.currentPage + 1 })">Next</a>
    }
</ul>
*@

@*@Html.PagedListPager(Model, i => Url.Action("Index", "UserRec1", new { i, searchText = Request.QueryString["searchText"] }))*@

@*<script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>*@

  

UserRecordForm/UserRecordForm/Views/UserRecord/deleteUser.cshtml
@*@model UserRecordForm.Models.UserRecord.UserRecord*@
@{
    ViewBag.Title = "DeleteUser";
}

<h2>deleteUser</h2>